# Generated by Django 3.2 on 2021-05-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='miniatura',
        ),
    ]
