# Generated by Django 3.2 on 2021-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_remove_image_miniatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('nombre',), 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('id',), 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterField(
            model_name='album',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='galeria', verbose_name='image'),
        ),
    ]
